// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz6g-dRmaaHANRQTZZx9d279Be1VcXjd4',
    appId: '1:558892593655:web:898f7b135554ac028cbef2',
    messagingSenderId: '558892593655',
    projectId: 'weatherapp-361e9',
    authDomain: 'weatherapp-361e9.firebaseapp.com',
    storageBucket: 'weatherapp-361e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWI5mj2O0Mu8JlYFeFzmd5HwJP8sjYHzI',
    appId: '1:558892593655:android:8648da2b4bc7149a8cbef2',
    messagingSenderId: '558892593655',
    projectId: 'weatherapp-361e9',
    storageBucket: 'weatherapp-361e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8s8ba-1OhjXfL13J769dlsk3lQtAcrA8',
    appId: '1:558892593655:ios:f6161dc7c8d3bfe58cbef2',
    messagingSenderId: '558892593655',
    projectId: 'weatherapp-361e9',
    storageBucket: 'weatherapp-361e9.appspot.com',
    iosBundleId: 'com.example.fe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8s8ba-1OhjXfL13J769dlsk3lQtAcrA8',
    appId: '1:558892593655:ios:f6161dc7c8d3bfe58cbef2',
    messagingSenderId: '558892593655',
    projectId: 'weatherapp-361e9',
    storageBucket: 'weatherapp-361e9.appspot.com',
    iosBundleId: 'com.example.fe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz6g-dRmaaHANRQTZZx9d279Be1VcXjd4',
    appId: '1:558892593655:web:80e89b57064601618cbef2',
    messagingSenderId: '558892593655',
    projectId: 'weatherapp-361e9',
    authDomain: 'weatherapp-361e9.firebaseapp.com',
    storageBucket: 'weatherapp-361e9.appspot.com',
  );

}